# Generated by Django 2.1.7 on 2019-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_auto_20191013_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinfo',
            name='date_added',
            field=models.DateField(),
        ),
    ]
